-
  name: VM-Standard
  priority: 1000
  action:
    type: Allow
  rules:
    -
      name: settings-win.data.microsoft.com
      direction: Inbound
      protocols:
        - https:443
      fqdnTags: []
      targetFqdns:
        - settings-win.data.microsoft.com
      actions: []
      sourceAddresses:
        - 172.0.0.0/24
    -
      name: download.windowsupdate.com
      direction: Inbound
      protocols:
        - https:443
      fqdnTags: []
      targetFqdns:
        - download.windowsupdate.com
      actions: []
      sourceAddresses:
        - 172.0.0.0/24
    -
      name: fe2.update.microsoft.com
      direction: Inbound
      protocols:
        - https:443
      fqdnTags: []
      targetFqdns:
        - fe2.update.microsoft.com
      actions: []
      sourceAddresses:
        - 172.0.0.0/24
    -
      name: sls.update.microsoft.com
      direction: Inbound
      protocols:
        - https:443
      fqdnTags: []
      targetFqdns:
        - sls.update.microsoft.com
      actions: []
      sourceAddresses:
        - 172.0.0.0/24
    -
      name: v10.vortex-win.data.microsoft.com
      direction: Inbound
      protocols:
        - https:443
      fqdnTags: []
      targetFqdns:
        - v10.vortex-win.data.microsoft.com
      actions: []
      sourceAddresses:
        - 172.0.0.0/24
    -
      name: ctldl.windowsupdate.com
      direction: Inbound
      protocols:
        - http:80
        - https:443
      fqdnTags: []
      targetFqdns:
        - ctldl.windowsupdate.com
      actions: []
      sourceAddresses:
        - 172.0.0.0/24
-
  name: Digicert
  priority: 1100
  action:
    type: Allow
  rules: 
    -
      name: crl3.digicert.com
      direction: Inbound
      protocols:
        - http:80
      targetFqdns:
        - crl3.digicert.com
      actions: []
      sourceAddresses:
        - 172.16.0.0/24
    -
      name: ocsp.digicert.com
      direction: Inbound
      protocols:
        - http:80
      targetFqdns:
        - ocsp.digicert.com
      actions: []
      sourceAddresses:
        - 172.16.0.0/24
